server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sale_management?useSSL=false&serverTimezone=UTC
    username: root
    password: chung2005
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Tự động tạo/sửa bảng (update/create/create-drop)
    show-sql: true        # Hiển thị câu lệnh SQL trên console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

#  thymeleaf:
#    cache: false          # Tắt cache để reload giao diện khi dev

  sql:
    init:
      mode: never    # Luôn chạy file schema/data nếu có
