server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salemanagement?useSSL=false&serverTimezone=UTC
    username: root
    password: chung2005
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      mode: always
